# Generated by Django 3.0.5 on 2020-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='last_request',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
